FROM ubuntu:16.04

LABEL maintainter="kzk_maeda"

# config ssh
RUN apt-get update && apt-get install -y openssh-server \
    && apt-get install -y rsyslog \
    && apt-get install -y vim
COPY ./keys/id_rsa /root/.ssh/id_rsa

CMD ["/bin/sh", "-c", "while :; do sleep 10; done"]